variables:
 - group: vargroup
 - name: connstr
   value: test

parameters:
  - name: environment
    displayName: Which Environment to deploy?
    type: string
    default: 'develop'
    values:
    - develop
    - preproduction
    - production

steps:
  - script:
     echo "Environment to deploy ${{parameters.environment}}"
     echo "##vso[task.setvariable variable=var1;] var1 value changed from test1"
     echo "variable group $(var1)"
    displayName: step1

