stages:
  - stage: devstage
    jobs:
     - job: getlatest
       steps:
        - script:          
           echo devstage_getlatest_step1
          displayName: stage1
     - job: buildstage
       steps:
        - script:
           echo devstage_buildstage_step1
  - stage: teststage
    jobs:
     - job: preparingdata
       steps:
        - script:          
           echo teststage_preparingdata_step1
          displayName: stage2
     - job: runtestcase
       steps:
        - script:
           echo teststage_runtestcase_step1